### ISSUE TITLE
Canal digital

### ISSUE THREAD

**Issue by neptr34** [devadvance/rootcloak#112]
Hi there, The 'Canal Digital' app wont run with root.
When using rootcloack the app starts, but crash after a second.

Running cm13 on galaxy S5

**Comment by Stliin** [comment]
Reinstalled CM13 on OnePlus3.
Fresh install, did not touch anything just installed Canal Digital go app.

The app reported the device rooted.
So this has something to do with the way CM13 works.

Installed OxygenOS the base os for the phone.
Installed the app and it worked.

**Comment by neptr34** [comment]
Thats why I tried with rootcloak. But when using rootcloak on the canal digital app, it crashes.

So if you root your phone with oxygen on and use rootcloak, it would work?

**Comment by Stliin** [comment]
To get root working i used Magisk V6.
But when i installed busybox it stopped working, i gues busybox midified /system :(

**Comment by neptr34** [comment]
Root I working just fine, and that's the 'problem' cause canal digital won't start when it detects root. That's why I tried to use rootcloack to hide root from canal digital. But when I installed rootcloack and added Canal digital to the list. The canal digital does not show the root warning, it just crashes when I run it instead.

**Comment by Stliin** [comment]
To get root UNDETECTED, use Magisk.
Rootcloak wont help. Some apps use the Google API to detect root.
Root Cloak wont help there, you need pure systemless root witch Magisk offer.

**Comment by neptr34** [comment]
I'll check it out, thanks!
