### ISSUE TITLE
Pokemon go v0.37

### ISSUE THREAD

**Issue by cire27rn** [devadvance/rootcloak#115]
Anyone tested root cloak and was able to play this?

**Comment by EbO96** [comment]
I tested root cloak, and unfortunately it's doesn't work :/ Any solution?

**Comment by kevlarcade** [comment]
Pokemon go is in the list so it should work but I can't launch pokemon. I tested with the latest stable version and latest beta (20160731_2) and still doesn't work for me. Maybe they are command or keyword to add in the list.

**Comment by hikaritenchi** [comment]
Unfortunately, Pokemon GO now uses SafetyNet, and RootCloak is unable to do anything about this.

**Comment by EbO96** [comment]
https://youtu.be/TBaZpiIDFQ8
12.09.2016 8:24 AM "kevlarcade" notifications@github.com napisał(a):
