### ISSUE TITLE
exec("su") is not cloaked on 5.0

### ISSUE THREAD

**Issue by sweetlilmre** [devadvance/rootcloak#14]
Runtime.getRuntime().exec("su");

This succeeds allowing root detection on a Samsung Galaxy S5 running The Galaxy Project ROM (stock, debloated).
Details:
Android 5.0
Builld number: LRX21T.G900FXXU1BOH4
ROM: http://forum.xda-developers.com/galaxy-s5/development/galaxy-project-galaxy-s5-t3138583
Xposed Framework: reported as version 65

**Comment by devadvance** [comment]
Try with version v1.52. Might have been the package name issue.

**Comment by sweetlilmre** [comment]
Confirmed working on v1.52!

Many thanks.
