### ISSUE TITLE
Hide USB debugging

### ISSUE THREAD

**Issue by pylerSM** [devadvance/rootcloak#17]
Some apps check if USB (ADB) debugging is enabled. If so, they refuse to work or disable some of their features.

I think I could implement "Hide USB debugging" feature into RootCloak, but I am not sure if RootCloak's developer wants this feature in this module or we/I should do it as a new Xposed module. So any opinion?

**Comment by devadvance** [comment]
Hiding USB debugging is a good idea. As long as it doesn't interrupt functionality, it's worth it.

**Comment by pylerSM** [comment]
https://github.com/devadvance/rootcloak/pull/18

**Comment by hikaritenchi** [comment]
Thanks! Released in RootCloak Prime.
