### ISSUE TITLE
New OVO application is not working.

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [devadvance/rootcloak#171]
https://play.google.com/store/apps/details?id=ovo.id

The new version of this app apparently got new root method.

And also I wanna ask you how to know which root detection method is used in certain app?

Thank you.

**Comment by hikaritenchi** [comment]
A lot of times nowadays, apps are moving towards SafetyNet, which is not something that RootCloak can do anything about. RootCloak just takes a "catch all detections" approach instead of targeting specific apps.

**Comment by Crescendo-BLYAT** [comment]
So, Magisk is the only way for SafetyNet then?
I'll give Magisk a go... 

It is suck to unroot...
Thanks for the reply...
