### ISSUE TITLE
merit unique su binary name

### ISSUE THREAD

**Issue by cultixate** [devadvance/rootcloak#3]
Would you see value in uniquely named binary and the convention of root enabled apps quering for actual path:

https://github.com/ChainsDD/Superuser/issues/65
https://github.com/koush/Superuser/issues/250

**Comment by devadvance** [comment]
This would be helpful, but there are a dozen different ways to check for a rooted phone beyond just the su binary name. For example, some apps check for the existence of root apps like SuperSU (https://play.google.com/store/apps/details?id=eu.chainfire.supersu).

Additionally, randomizing the su binary name on install might work for apps that check for it, but it would eliminate the ability for root apps to execute "su", which many depend on.
