### ISSUE TITLE
The Xposed API classes are compiled into the module's APK

### ISSUE THREAD

**Issue by Phoenix09** [devadvance/rootcloak#36]
> 05-28 15:58:37.330 I/Xposed  ( 3154): Loading modules from /data/app/com.devadvance.rootcloak2-1/base.apk
> 05-28 15:58:37.360 W/Xposed  ( 3154):   The Xposed API classes are compiled into the module's APK.
> 05-28 15:58:37.360 W/Xposed  ( 3154):   This may cause strange issues and must be fixed by the module developer.
> 05-28 15:58:37.370 W/Xposed  ( 3154):   For details, see: http://api.xposed.info/using.html

this needs to be changed which took me 30 seconds.

> Finally, a word to all module developers: In v84, I added a warning when a module's APK includes the Xposed API classes instead of just referencing them. I have also sent an email to the developers of all modules I could identify. **With v86, I will turn the warning into an error and prevent the module from loading**, as it could causes strange issues otherwise. Please update your module as soon as possible.

[source](http://forum.xda-developers.com/showthread.php?s=170ea1c75bd6306f78e18d4b64c74d22&t=3034811&page=4)

**Comment by hikaritenchi** [comment]
Thanks, I'll take a look. It might take a little bit of time to get it to the xposed repo, since I've never done it before.

**Comment by hikaritenchi** [comment]
fixed with RootCloak Prime release.
