### ISSUE TITLE
Fix CI to work for pull requests

### ISSUE THREAD

**Issue by devadvance** [devadvance/rootcloak#45]
Fix should just be to change the yml file to do an assemble for pull requests instead of assembleRelease

**Comment by hikaritenchi** [comment]
assembleRelease should be working too though...since I added the gradle directive to not abort on lint errors...?

**Comment by devadvance** [comment]
It's due to how travis works. I have the encrypted signing config variables in the yml file, but those only work for changes within devadvance/rootcloak repo. For pull requests coming from forks, those variables are unavailable due to security constraints.

https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests

**Comment by devadvance** [comment]
Fixing the issue with #49
