### ISSUE TITLE
Should we add native hooking to RootCloak?

### ISSUE THREAD

**Issue by devadvance** [devadvance/rootcloak#46]
I'm not a huge fan of bringing parts of this down to native, as it really starts to break the Xposed box. It also runs into SELinux issues, which is a problem I had with Cydia Substrate. But perhaps it warrants a second look?

Example: https://github.com/HiddenRambler/rootcloak/commit/b94901608a44e07daaec1cfd1b126cd552ea322e

**Comment by hikaritenchi** [comment]
Native checks have been requested, and there are other root hiding apps that successfully implement them, if only for one target app. I was going to work on a more general strategy for this, but I don't know anything about SELinux issues.

**Comment by pylerSM** [comment]
this is very interesting imho.. If merged, I would put it as experimental setting...

**Comment by pylerSM** [comment]
And what about LD_PRELOAD trick? We can compile our so library with our custom fopen/etc/etc implementations and then just
setprop com.app.rootcheck LD_PRELOAD=/path/to/library.so
?

**Comment by nguyenvulong** [comment]
@hikaritenchi cloud you please give me some examples about apps that implement evading techniques that hide from native checks?
Any app is fine, especially if they're open for community on github. Thanks in advance!

**Comment by devadvance** [comment]
@nguyenvulong check https://github.com/devadvance/rootcloak/wiki/Working-and-Nonworking-Apps under the section titled "Apps with calls most likely can never be directly intercepted by Xposed". Several of those use native checking.

**Comment by devadvance** [comment]
See #62 for continuing the discussion.
