### ISSUE TITLE
Patches support

### ISSUE THREAD

**Issue by pylerSM** [devadvance/rootcloak#52]
Some apps may require hooking of some special methods to disable root detection. Maybe we could introduce support for this so RootCloak can "load" required data to hook from file (packagename.rootcloack, for example) and hook that methods. We could avoid situatuion when there are so many small xposed mods just to remove root from specific apps.

Maybe patch could be simple file with structure

"CLASS", "METHOD", "RETURNVALUE".   (usually enough)
"CLASS2", "METHOD2", "RETURNVALUE2".  (optionally if needed, so support for more clases)

Later we could talk about one place to store these "patches", fetch them online or so...

**Comment by pylerSM** [comment]
Also maybe in app system to patch known native libs for detection of roob (libshield.so, libtool-checker.so). Or maybe provide prepatched versions and RootCloak would replace original version with prepatched one.

**Comment by hikaritenchi** [comment]
I was thinking about something similar to this too, where we can load in from somewhere like Firebase. It would make the app more data-driven, but then you wouldn't be able to rely on something like v2.0.5 of rootcloak working with "v5.33 of SecureApp" for example. It's definitely something to consider.

Also see #16

**Comment by devadvance** [comment]
The two major issues I would foresee with this are the versioning problem you mention @hikaritenchi as well as the scaling problem. As much as I'm not a huge fan of going outside of Xposed and doing native patching, it seems to be more scalable (i.e. write once, cover many apps).

Neither really touches the SafetyNet problem, and there are a few methods to detect system modification in general that are harder to address.

**Comment by pylerSM** [comment]
Since we have this https://github.com/devadvance/rootcloak/issues/62 I closed this issue
