### ISSUE TITLE
Option to Hide XPosed

### ISSUE THREAD

**Issue by googolydox** [devadvance/rootcloak#55]
Apps like Snapchat check for xposed and reject users, but rootcloak does not cloak xposed, despite the fact that rootcloak needs xposed to work

**Comment by devadvance** [comment]
RootCloak already includes "xposed" as a keyword to hide. However, Snapchat is checking for more than this. See: https://github.com/pylerSM/NoDeviceCheck/issues/3#issuecomment-226975180
