### ISSUE TITLE
Add browse feature pls

### ISSUE THREAD

**Issue by exodius48** [devadvance/rootcloak#58]
It will better than input manual package name.

**Comment by pylerSM** [comment]
There is app picker but icon is very weird, dark on dark. We need fixed icon @devadvance

**Comment by exodius48** [comment]
@pylerSM where is located?

**Comment by pylerSM** [comment]
Customize Apps , next to the "Menu" icon... it is a "+" icon.

**Comment by pylerSM** [comment]
and it is "ic_action_new.png"

**Comment by exodius48** [comment]
Oh..i see it. The icon is very dark on lollipop rom. I can't see it very well.

**Comment by pylerSM** [comment]
Fix is here https://github.com/devadvance/rootcloak/pull/60 ... @devadvance ?

**Comment by hikaritenchi** [comment]
Fixed with #60
