### ISSUE TITLE
Toggling Debug buggy

### ISSUE THREAD

**Issue by dwendt** [devadvance/rootcloak#78]
Hey, there's currently a long toast that is popped when you click to toggle debug. This makes it pretty confusing to try to toggle the debug preference, as there's no way to see what the current value is. Also, for me, it seems like the activity always assumes debug is off. You can toggle deug on, close the activity, and pop the activity to disable debug. It'll toast "Debug turned on!" in that case, still.

**Comment by pylerSM** [comment]
It will be improved. https://github.com/devadvance/rootcloak/pull/76

**Comment by Phoenix09** [comment]
@pylerSM, should probably change it to a checkbox

**Comment by pylerSM** [comment]
Well, PreferenceActivity would be better idea yes, but until current patches are not merged, I see no reason to work further.

**Comment by pylerSM** [comment]
@devadvance  can you merge this patch https://github.com/pylerSM/rootcloak/commit/ebc24589dfefe9823a38ad2e1edfefac6fc9e614?

**Comment by devadvance** [comment]
Merged.
