### ISSUE TITLE
doesn't work on lollipop

### ISSUE THREAD

**Issue by mountainguan** [devadvance/rootcloak#8]
when set an app to hide form rootcheck,it will be force closed.I hope author can fix this problem on Android 5.0.THX

**Comment by me21** [comment]
Someone has already fixed the issue and notified the author. However, the fixed version is kept private, but you can ask for it in PM: http://forum.xda-developers.com/showpost.php?p=62218425&postcount=795

**Comment by devadvance** [comment]
I pulled in commits and published a new version that *should* fix this issue. The commits are (largely) the same, so there shouldn't be any issues if the version that you (@me21) worked already.

http://repo.xposed.info/module/com.devadvance.rootcloak2

**Comment by devadvance** [comment]
Based on XDA feedback, should be working as of v1.52
