### ISSUE TITLE
Automatically "hide root" for newly installed apps

### ISSUE THREAD

**Issue by pylerSM** [devadvance/rootcloak#91]
After all PR's got merged, I would like to work on this. 

Ideas? Worth to work on this? Please comment what would be the best.

**Comment by devadvance** [comment]
I think the percentage of apps that check for root is small enough that users will end up removing most of the new apps that get automatically added.

**Comment by pylerSM** [comment]
Ok

**Comment by pylerSM** [comment]
Well, I thought that apps may detect root/xposed at first launch and then save result to shared prefs and then when we apply rootcloak, it has no effect...

**Comment by hikaritenchi** [comment]
That is a fairly good reason to consider this enhancement...Worse, the app could "phone home" and the user's device might be blacklisted on the server, and even clear data/uninstall might not fix it...

**Comment by pylerSM** [comment]
Android device id / imei could be faked then too..
